const fs = require('fs');
const raw = fs.readFileSync('app/[locale]/tours/page.tsx');
const str = raw.toString('latin1');
const idx = str.indexOf("'City Tours': '", 500);
console.log('idx:', idx);
const slice = raw.slice(idx + 15, idx + 25);
console.log([...slice].map(b => b.toString(16).padStart(2,'0')).join(' '));
const bad = Buffer.from(slice);
const good = Buffer.from([0xF0, 0x9F, 0x8F, 0x99, 0xEF, 0xB8, 0x8F]);
console.log('bad bytes:', [...bad].map(b => b.toString(16).padStart(2,'0')).join(' '));
const newRaw = Buffer.concat([raw.slice(0, idx+15), good, raw.slice(idx+15+bad.length)]);
fs.writeFileSync('app/[locale]/tours/page.tsx', newRaw);
console.log('done');
